target-dir: "/Users/cristianquiroz/dev/magento/builds/indexer"
clean: true                     #Removes current content from the target directory
clean-exceptions:               #Files or directories that should be kept during cleaning (local to target-dir)
  - "app/etc/local.xml"

dir-paths:                      #List of directories to symlink into target directory
  - "/Users/cristianquiroz/dev/magento/versions/enterprise11400/"
  - "/Users/cristianquiroz/dev/magento/clones/indexer/"

composer: true                  #Should composer be run
post-composer-dir-paths:        #List of directories to symlink into target directory after running composer

grunt: false                     #Should grunt be run